--SQL ADVANCE CASE STUDY


--Q1--BEGIN 
	
	
	SELECT DISTINCT L.STATE 
	FROM FACT_TRANSACTIONS AS T
	JOIN DIM_LOCATION AS L
	ON T.IDLOCATION=L.IDLOCATION
	WHERE T.DATE >= '2005-01-01'
	 
	

--Q1--END

--Q2--BEGIN
	


	SELECT TOP 1 L.STATE  
	FROM FACT_TRANSACTIONS AS T
	
	JOIN DIM_LOCATION AS L
	ON L.IDLOCATION=T.IDLOCATION
	JOIN DIM_MODEL AS ML
	ON ML.IDMODEL=T.IDMODEL
	JOIN DIM_MANUFACTURER AS MF
	ON ML.IDMANUFACTURER=MF.IDMANUFACTURER
	
	WHERE MF.MANUFACTURER_NAME= 'SAMSUNG'
	AND L.COUNTRY='US'
	GROUP BY L.STATE
	ORDER BY SUM (T.QUANTITY) DESC
	







--Q2--END

--Q3--BEGIN      
	

	SELECT  ML.MODEL_NAME,L.ZIPCODE,L.STATE,COUNT(T.IDLOCATION) AS [TRANSACTION COUNT]
	FROM FACT_TRANSACTIONS AS T
	JOIN DIM_LOCATION AS L
	ON L.IDLOCATION=T.IDLOCATION
	JOIN DIM_MODEL AS ML
	ON ML.IDMODEL=T.IDMODEL
	GROUP BY ML.MODEL_NAME,L.ZIPCODE,L.STATE






--Q3--END

--Q4--BEGIN



	SELECT DISTINCT TOP 1  
	MF.MANUFACTURER_NAME+' '+ ML.MODEL_NAME AS [PHONE NAME] ,
	ML.UNIT_PRICE
	FROM FACT_TRANSACTIONS AS T
	JOIN DIM_MODEL AS ML
	ON ML.IDMODEL=T.IDMODEL
	JOIN DIM_MANUFACTURER AS MF
	ON MF.IDMANUFACTURER=ML.IDMANUFACTURER
	ORDER BY ML.UNIT_PRICE






--Q4--END

--Q5--BEGIN



	SELECT ML.MODEL_NAME ,AVG(TOTALPRICE) AS [AVERAGE PRICE] FROM FACT_TRANSACTIONS AS T
	JOIN DIM_MODEL AS ML
	ON ML.IDMODEL=T.IDMODEL
	JOIN DIM_MANUFACTURER AS MF
	ON MF.IDMANUFACTURER=ML.IDMANUFACTURER
	WHERE MF.MANUFACTURER_NAME IN (SELECT TOP 5 MF.MANUFACTURER_NAME 							  FROM FACT_TRANSACTIONS AS T
									JOIN DIM_MODEL AS ML
									ON ML.IDMODEL=T.IDMODEL
									JOIN DIM_MANUFACTURER AS MF
									ON MF.IDMANUFACTURER=ML.IDMANUFACTURER
									GROUP BY MF.MANUFACTURER_NAME
									ORDER BY SUM(T.QUANTITY) DESC) 
	GROUP BY ML.MODEL_NAME
	ORDER BY [AVERAGE PRICE] DESC
	
	   	  

--Q5--END

--Q6--BEGIN



	SELECT C.CUSTOMER_NAME, 
	AVG(TOTALPRICE) AS [AVERAGE AMOUNT SPENT]
	FROM FACT_TRANSACTIONS AS T
	JOIN DIM_CUSTOMER AS C
	ON C.IDCUSTOMER=T.IDCUSTOMER
	WHERE YEAR (T.DATE) =2009 
	GROUP BY C.CUSTOMER_NAME
	HAVING AVG(TOTALPRICE) >500
	
	

	   	  
--Q6--END
	
--Q7--BEGIN  
	
	SELECT * FROM (SELECT TOP 5 ML.MODEL_NAME
	FROM FACT_TRANSACTIONS AS T
	JOIN DIM_MODEL AS ML
	ON ML.IDMODEL=T.IDMODEL
	WHERE YEAR(DATE)=2008
	GROUP BY ML.MODEL_NAME
	ORDER BY SUM(QUANTITY) DESC) AS X

				 INTERSECT

	SELECT * FROM (SELECT TOP 5 ML.MODEL_NAME FROM FACT_TRANSACTIONS AS T
	JOIN DIM_MODEL AS ML
	ON ML.IDMODEL=T.IDMODEL
	WHERE YEAR(DATE)=2009
	GROUP BY ML.MODEL_NAME
	ORDER BY SUM(QUANTITY) DESC) AS Y

				 INTERSECT
				 
	 SELECT * FROM (SELECT TOP 5 ML.MODEL_NAME FROM FACT_TRANSACTIONS AS T
	 JOIN DIM_MODEL AS ML
	 ON ML.IDMODEL=T.IDMODEL
	 WHERE YEAR(DATE)=2010
	 GROUP BY ML.MODEL_NAME
	 ORDER BY SUM(QUANTITY) DESC ) AS Z
			


--Q7--END	
--Q8--BEGIN


	SELECT MANUFACTURER_NAME,
		   YEARS 
	FROM(
		  SELECT MF.MANUFACTURER_NAME,YEAR(DATE) AS YEARS,
		  DENSE_RANK() OVER ( ORDER BY SUM(T.TOTALPRICE) DESC) AS RANKS 
		  FROM FACT_TRANSACTIONS AS T
		  JOIN  DIM_MODEL AS ML
		  ON ML.IDMODEL=T.IDMODEL
		  JOIN DIM_MANUFACTURER AS MF
		  ON MF.IDMANUFACTURER=ML.IDMANUFACTURER
		  WHERE YEAR(DATE)= 2009
		  GROUP BY MF.MANUFACTURER_NAME,YEAR(DATE)
	    )  AS X
	WHERE RANKS =2
	
	UNION ALL

	SELECT MANUFACTURER_NAME,
		   YEARS 
	FROM(
			SELECT MF.MANUFACTURER_NAME,YEAR(DATE) AS YEARS,
			DENSE_RANK() OVER ( ORDER BY SUM(T.TOTALPRICE) DESC) AS RANKS
			FROM FACT_TRANSACTIONS AS T
			JOIN  DIM_MODEL AS ML
			ON ML.IDMODEL=T.IDMODEL
			JOIN DIM_MANUFACTURER AS MF
			ON MF.IDMANUFACTURER=ML.IDMANUFACTURER
			WHERE YEAR(DATE)= 2010
			GROUP BY MF.MANUFACTURER_NAME,YEAR(DATE)
		)	AS Y
	WHERE RANKS =2
		
	
	
--Q8--END
--Q9--BEGIN
	


	SELECT MF.MANUFACTURER_NAME FROM FACT_TRANSACTIONS AS T
	JOIN  DIM_MODEL AS ML
	ON ML.IDMODEL=T.IDMODEL
	JOIN DIM_MANUFACTURER AS MF
	ON MF.IDMANUFACTURER=ML.IDMANUFACTURER
	WHERE YEAR(DATE)=2010
	
	EXCEPT

	SELECT MF.MANUFACTURER_NAME FROM FACT_TRANSACTIONS AS T
	JOIN  DIM_MODEL AS ML
	ON ML.IDMODEL=T.IDMODEL
	JOIN DIM_MANUFACTURER AS MF
	ON MF.IDMANUFACTURER=ML.IDMANUFACTURER
	WHERE YEAR(DATE)=2009



	   	  

--Q9--END

--Q10--BEGIN
	

	WITH TOP_10 AS(
					SELECT * 
					FROM
						(SELECT  YEAR(T.DATE) AS YEARS,T.IDCUSTOMER,
						AVG(T.TOTALPRICE) AS AVGSPEND,
						AVG(T.QUANTITY) AS AVGQTY,
						DENSE_RANK() OVER (PARTITION BY YEAR(T.DATE) ORDER BY AVG(T.TOTALPRICE) DESC ) AS RANKS
						FROM FACT_TRANSACTIONS AS T
						GROUP BY YEAR(T.DATE),T.IDCUSTOMER
				  ) AS X
					WHERE RANKS<=10),
			
	YEAR_WISE_SPEND AS(
						SELECT IDCUSTOMER,YEARS,AVGSPEND,AVGQTY,
						LAG (AVGSPEND,1) OVER (PARTITION BY IDCUSTOMER ORDER BY IDCUSTOMER,YEARS) AS PREV_SPEND
						FROM TOP_10
					   ),
	
	PERCENT_CHANGE 	AS ( SELECT *, (AVGSPEND-PREV_SPEND)/PREV_SPEND*100 AS [YOY %CHANGE]
						 FROM YEAR_WISE_SPEND)
	
	SELECT IDCUSTOMER,YEARS,AVGQTY,AVGSPEND,[YOY %CHANGE] 
	FROM PERCENT_CHANGE 
	
--Q10--END
	